version: '3'

services:
  ssh:
    image: rastasheep/ubuntu-sshd
    ports:
      - "2222:22"
    volumes:
      - "./home:/home"

  nginx:
    image: catwater1233/4132202-3-64-lab3:lastest
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - ssh