version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_test
    ports:
      - "3306:3306"
  nginx:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
